# Generated by Django 2.1.3 on 2018-11-08 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('account_name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=11)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
